version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # expose le port 3000 pour accéder à ton app Next.js
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/mydatabase
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # expose le port 5432 si tu souhaites y accéder localement

volumes:
  postgres-data:
