import type { Metadata } from "next";
import "./styles/globals.css"
import { SimpleNav } from "./components/simple-nav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <SimpleNav/>
          </nav>
        </header>
        <main>
          {children}
        </main> 
      </body>
    </html>
  );
}
