name: Deploy with Docker Compose

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' 

    - name: Log in to Docker Hub
      run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build the docker image & test
      id: build-docker-image
      run: |
          docker build -t mcuron/client-connect:latest .  #\
          # --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
          # --build-arg NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
          # -t mcuron/client-connect:latest .           
          # >
          # dotnet test
          # --configuration Release
          # --logger GitHubActions
          # --
          # RunConfiguration.CollectSourceInformation=true
    
    - name: Push the docker image
      id: push-docker-image
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
          docker push mcuron/client-connect:latest 

